spring:
  application:
    name: sentinel-zookeeper-provider
## dubbo 配置
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
    logger: slf4j
  scan:
    base-packages: com.flash.framework.sentinel.demo.api.impl
  protocol:
    name: dubbo
    port: 20880
  registry:
    check: false
    address: zookeeper://127.0.0.1:2181
    simplified: true
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  config-center:
    address: zookeeper://127.0.0.1:2181
sentinel:
  dashboard-server: localhost:8080
  ## 限流规则后缀
  flow-rule-data-id-suffix: -flow-rules
  ## 单机模式
  mode: LOCAL
  remote-address: 127.0.0.1:8848
  datasource: NACOS
  nacos-group-id: sentinel-demo

